### ISSUE TITLE
This package (cf binary) likley has to be GPL licensed due to linking against FFTW

### ISSUE THREAD

**Issue by moorepants** [conda-forge/openmm-feedstock#24]
We came to the conclusion here:

conda-forge/pyshtools-feedstock#3

that the Conda Forge binaries that link against FFTW have to be GPL licensed. This would likely the case for this package too.

**Comment by peastman** [comment]
OpenMM contains no GPL code.  Therefore, it doesn't need to use the GPL license.

It has the ability to dynamically link to FFTW at runtime (though it also can work fine without it).  To ensure the user has the legal right to link them, it needs to have a license that is GPL compatible, which it does.  The Free Software Foundation has a FAQ that discusses this issue in lots of detail.  Here are some of the most relevant parts.

https://www.gnu.org/licenses/gpl-faq.html#LinkingWithGPL
https://www.gnu.org/licenses/gpl-faq.html#WhatIsCompatible
https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean

**Comment by moorepants** [comment]
So, in this case releasing this binary under the LGPL means it is compatible with the GPL? I would think the LGPL is incompatible with the GPL in that sense, since the ability to dynamically link against downstream libraries is relaxed in the GPL.

**Comment by moorepants** [comment]
I read this: https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License#Compatibility but I'm not sure I understand it clearly. It is clear that you can link to LGPL code and then license as GPL, but I'm hazy on whether you can do the opposite.

**Comment by moorepants** [comment]
I guess if FFTW says "GPL 2 or later" then you may license as LGPL.

**Comment by moorepants** [comment]
FFTW is GPL 2 or later: http://www.fftw.org/doc/License-and-Copyright.html

**Comment by peastman** [comment]
See the FSF's list of licenses at https://www.gnu.org/licenses/license-list.html.  For each one they note whether it's GPL compatible.  LGPL and MIT are both GPL compatible, because they don't impose any restrictions beyond those found in the GPL.

**Comment by moorepants** [comment]
>  LGPL and MIT are both GPL compatible, because they don't impose any restrictions beyond those found in the GPL.

There are two directions of compatibility. i.e. you can link to MIT code and license your code as GPL but you can't link to GPL code and license your code as MIT. So I think you have to ask "what licenses are compatible with the LGPL?" if you want to release openmm as LGPL here. I'm not sure that GPL is compatible with LGPL. I'm trying to find a list of what licenses are compatible with LGPL. What you've stated is that LGPL is compatible with GPL, not the other way around.

**Comment by peastman** [comment]
OpenMM contains no GPL code.  It only contains code that either we wrote ourselves, or that is distributed under a very permissive BSD style license.  We can of course distribute our own code under any license we want, but we need to make sure we also respect the licenses of all other code we've incorporated.  Since they all have very permissive licenses, that isn't a problem.

Further issues come up when a user executes it, and it gets dynamically linked to FFTW in their computer's memory.  We want to make sure the user isn't violating any licenses by doing that.  LGPL imposes no restrictions on dynamic linking, so there's no problem as far as it's concerned.  GPL does impose restrictions on it, so that's the direction of compatibility we need to worry about.  If you dynamically linked it to a library that wasn't GPL compatible, you would be violating the terms of the GPL.

Of course, there are other ways of dealing with this.  You can also buy commercial licenses for FFTW that let you link it to proprietary software.  But we don't want our users to have to do that.  But the important thing is that, one way or another, the user needs to be able to execute it without violating any terms of the license on either OpenMM or FFTW.

**Comment by isuruf** [comment]
I agree that the source code of OpenMM can remain BSD or any other GPL compatible license. The binaries that we distribute through conda are GPL licensed because they link to FFTW right?

**Comment by moorepants** [comment]
> The binaries that we distribute through conda are GPL licensed because they link to FFTW right?

That's the point I'm trying to make. openmm conda binaries dynamically link against FFTW which is released under the GPL 2.0 or later, thus the conda openmm binary has to be licensed with GPL 2.0 or later.

**Comment by peastman** [comment]
The conda package for OpenMM doesn't include FFTW.  Therefore as far as distribution is concerned, it doesn't matter what the FFTW license is.

Technically speaking, the "combined package" consisting of OpenMM linked to FFTW only ever exists in the memory of a computer that's running it.  That's the point where they actually get linked: not when they're distributed, but when the two packages are loaded into memory and the OS links them together.  The issue of license compatibility is to ensure that combined package can be created in a way that doesn't violate the licenses on any of the individual components that are being combined.

A few examples might help.  Suppose you load into memory and link together two libraries: one distributed under LGPL and the other distributed under GPL.  This is fine.  The GPL requires that the combined package (which, remember, exists only in memory, not on disk) be usable under the terms of the GPL.  Since the LGPL explicitly grants the right to relicense it under the GPL, this doesn't cause any problems.  And again, this only applies to the "combined package" that exists in memory.  It doesn't impact the separate packages stored on disk.

Now suppose you want to link two libraries that are distributed under the GPL and AGPL, respectively.  That isn't permitted.  Despite its name, the AGPL is not a GPL-compatible license.  There is no set of terms the combined package could be placed under that would satisfy the requirements of both licenses.  Therefore, any user who created that combined package by linking those two libraries together would be violating the terms of one of the two licenses.

If all of this logic sounds abstract and unintuitive, that's because it was invented by lawyers. :)

The [FSF FAQ](https://www.gnu.org/licenses/gpl-faq.html#LinkingWithGPL) does state the requirements very clearly:

> **You have a GPLed program that I'd like to link with my code to build a proprietary program. Does the fact that I link with your program mean I have to GPL my program? (#LinkingWithGPL)**
>
>    Not exactly. It means you must release your program under a license compatible with the GPL (more precisely, compatible with one or more GPL versions accepted by all the rest of the code in the combination that you link). The combination itself is then available under those GPL versions.

**Comment by moorepants** [comment]
@peastman Thanks for taking the time to explain the nuances. I understand the quoted section in the last message now. The fact that this only matters wrt to the linked code in your computer's memory makes this very un-intuitive. I thought that these licenses were stating rules regarding the public distribution of codes not rules regarding what license is applied if the code is linked in the memory of a particular computer.

I was under the impression that if you use any API declared in the header's of a GPL licensed code in your code and for the purpose of dynamically linking to that GPL library and you then distribute your code, you must licensed your code as GPL. I also was under the impression that the LGPL was created, in part, to relax that particular stringent element of the GPL.

If what @peastman wrote is correct here, I think then the ruling made in https://github.com/conda-forge/pyshtools-feedstock/issues/3 may be incorrect.

**Comment by jakirkham** [comment]
Probably better surface as [an issue on the webpage repo]( https://github.com/conda-forge/conda-forge.github.io/issues ) and ping core for feedback. The conclusion can be written up in the docs and next steps taken.

**Comment by moorepants** [comment]
> The conclusion can be written up in the docs and next steps taken.

Yes, this would be very helpful to clearly explain the conda forge docs.

**Comment by moorepants** [comment]
Opened here: https://github.com/conda-forge/conda-forge.github.io/issues/1065

**Comment by jakirkham** [comment]
Thanks! :)
